import jsPDF from 'jspdf';
import 'jspdf-autotable';
// Note: QRCode generation for PDF typically requires converting canvas to image.
// Ideally, we generate the QR code as a Data URL and pass it to jsPDF.

export const exportReceiptToPDF = (receiptData) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Indigo
    doc.text("OFFICIAL RECEIPT", 105, 20, null, null, "center");

    // Receipt Details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    let y = 40;
    const addLine = (label, value) => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${label}:`, 20, y);
        doc.setFont('helvetica', 'normal');
        doc.text(`${value}`, 60, y);
        y += 10;
    };

    addLine("Receipt No", receiptData.receipt_number);
    addLine("Date", receiptData.date);
    addLine("Payer", `${receiptData.payer_type} - ${receiptData.payer_id}`); // Ideally resolve name
    addLine("Amount", `${receiptData.amount} ${receiptData.currency || 'Fbu'}`);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by FinApp System", 105, 280, null, null, "center");

    doc.save(`Receipt-${receiptData.receipt_number}.pdf`);
};

export const exportJournalToPDF = (entries) => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Journal Entries", 14, 20);

    const tableColumn = ["Date", "Type", "Amount", "Currency", "Account", "Balance"];
    const tableRows = entries.map(entry => [
        entry.date,
        entry.type,
        entry.amount,
        entry.currency,
        entry.account_id, // Ideally resolve name
        entry.balance_after
    ]);

    doc.autoTable({
        head: [tableColumn],
        body: tableRows,
        startY: 30,
    });

    doc.save("Journal_Entries.pdf");
};
